language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r test_requirements.txt
  - pip install coveralls
script: make coverage
after_success: coveralls
branches:
  only: master